"""feat_db_phase_4b_projects_alumni

Revision ID: 2c2d14776b6e
Revises: a1b2c3d4e5f6
Create Date: 2026-09-25 11:25:35.711912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c2d14776b6e'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alumni',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('reg_no', sa.String(length=20), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=False),
    sa.Column('program', sa.String(length=50), nullable=True),
    sa.Column('degree', sa.String(length=20), nullable=True),
    sa.Column('current_company', sa.String(length=200), nullable=True),
    sa.Column('current_role', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('github_url', sa.String(length=500), nullable=True),
    sa.Column('portfolio_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('open_to_mentorship', sa.Boolean(), nullable=True),
    sa.Column('open_to_hiring', sa.Boolean(), nullable=True),
    sa.Column('willing_to_visit', sa.Boolean(), nullable=True),
    sa.Column('privacy_level', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('reg_no'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_alumni_company', 'alumni', ['current_company'], unique=False)
    op.create_index('idx_alumni_grad_year', 'alumni', ['graduation_year'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('slug', sa.String(length=350), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('tech_stack', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('domain', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('github_url', sa.String(length=500), nullable=True),
    sa.Column('demo_url', sa.String(length=500), nullable=True),
    sa.Column('paper_url', sa.String(length=500), nullable=True),
    sa.Column('mentor_id', sa.UUID(), nullable=True),
    sa.Column('external_mentor', sa.String(length=200), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('outcomes', sa.String(), nullable=True),
    sa.Column('awards', sa.String(length=300), nullable=True),
    sa.Column('revenue_generated', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('client_name', sa.String(length=200), nullable=True),
    sa.Column('cover_image_url', sa.String(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['mentor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('idx_projects_domain_status', 'projects', ['domain', 'status'], unique=False)
    op.create_index('idx_projects_mentor', 'projects', ['mentor_id'], unique=False)
    op.create_index('idx_projects_tech_stack', 'projects', ['tech_stack'], unique=False, postgresql_using='gin')
    op.create_table('alumni_experience',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('alumni_id', sa.UUID(), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=200), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alumni_id'], ['alumni.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alumni_exp_alumni', 'alumni_experience', ['alumni_id'], unique=False)
    op.create_table('project_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_proj_doc_project', 'project_documents', ['project_id'], unique=False)
    op.create_table('project_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_proj_member_unique', 'project_members', ['project_id', 'student_id'], unique=True)
    op.create_index('idx_alumni_mentor', 'alumni', ['open_to_mentorship'], unique=False, postgresql_where=sa.text('open_to_mentorship = true'))
    op.execute("CREATE INDEX IF NOT EXISTS idx_projects_search ON projects USING gin(to_tsvector('english', title || ' ' || COALESCE(summary, '')))")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS idx_projects_search")
    op.drop_index('idx_alumni_mentor', table_name='alumni')
    op.drop_index('idx_proj_member_unique', table_name='project_members')
    op.drop_table('project_members')
    op.drop_index('idx_proj_doc_project', table_name='project_documents')
    op.drop_table('project_documents')
    op.drop_index('idx_alumni_exp_alumni', table_name='alumni_experience')
    op.drop_table('alumni_experience')
    op.drop_index('idx_projects_tech_stack', table_name='projects', postgresql_using='gin')
    op.drop_index('idx_projects_mentor', table_name='projects')
    op.drop_index('idx_projects_domain_status', table_name='projects')
    op.drop_table('projects')
    op.drop_index('idx_alumni_grad_year', table_name='alumni')
    op.drop_index('idx_alumni_company', table_name='alumni')
    op.drop_table('alumni')
    # ### end Alembic commands ###
